# fly.toml app configuration file generated for tictactoe-rust-backend on 2023-06-27T21:49:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tictactoe-rust-backend"
primary_region = "bos"

[env]
RUST_LOG = "info,tictactoe_rs=trace,tower_http=trace"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1200
    soft_limit = 1000
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
