# fly.toml app configuration file generated for tictactoe-elixir-backend on 2023-06-04T09:02:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tictactoe-elixir-backend"
primary_region = "bos"

[env]
  PORT = 3000
  FRONTEND_URL = "https://svelte-frontend-mu.vercel.app/"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 300
    soft_limit = 200

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"