name: Deploy Elixir Backend
on:
  push:
    branches:
      - main
    paths:
      - 'elixir-backend/**/*'
      - '.github/workflows/elixir-backend.yml'
env:
  FLY_API_TOKEN: ${{ secrets.ELIXIR_TOKEN }}
jobs:
  deploy:
    name: Deploy Elixir Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        working-directory: elixir_backend
        run: flyctl deploy --remote-only
